DATASET_PATH = "TrashCan/instance_version/"
AUGMENTED_DATASET_PATH = "augmented_dataset/"
LORA_PATH = "weights/"
LORA_WEIGHTS = "LoRA_2_pytorch_lora_weights.safetensors"
FOCUS_NET_PATH = "weights/FocusNetv4_Mbasic_padding_LL1+IOU_OSGD_LR0.065_E150.pth"

category_labels = {
    1: "rov",
    2: "plant",
    3: "animal_fish",
    4: "animal_starfish",
    5: "animal_shells",
    6: "animal_crab",
    7: "animal_eel",
    8: "animal_etc",
    9: "trash_clothing",
    10: "trash_pipe",
    11: "trash_bottle",
    12: "trash_bag",
    13: "trash_snack_wrapper",
    14: "trash_can",
    15: "trash_cup",
    16: "trash_container",
    17: "trash_unknown_instance",
    18: "trash_branch",
    19: "trash_wreckage",
    20: "trash_tarp",
    21: "trash_rope",
    22: "trash_net",
}

prompts = {
    1: "an underwater remotely operated vehicle (ROV), realistic, blending with the environment",
    2: "an underwater plant, swaying gently, realistic, blending with the marine environment",
    3: "a fish swimming underwater, realistic, blending with the marine environment",
    4: "a starfish resting on the seabed, realistic, blending with the marine environment",
    5: "a collection of underwater shells on the seabed, realistic, blending with the environment",
    6: "a crab walking on the ocean floor, realistic, blending with the marine environment",
    7: "an eel hiding in rocks or coral underwater, realistic, blending with the marine environment",
    8: "a small underwater animal, realistic, blending with the marine environment",
    9: "a piece of clothing as trash underwater, realistic, blending with the environment",
    10: "a metal pipe as trash underwater, realistic, blending with the environment",
    11: "a discarded bottle underwater, realistic, blending with the marine environment",
    12: "a plastic bag as trash underwater, realistic, blending with the marine environment",
    13: "a snack wrapper as trash underwater, realistic, blending with the marine environment",
    14: "a discarded can as trash underwater, realistic, blending with the marine environment",
    15: "a plastic cup as trash underwater, realistic, blending with the marine environment",
    16: "a container as trash underwater, realistic, blending with the marine environment",
    17: "an plastic trash object underwater, realistic, blending with the marine environment",
    18: "a branch floating underwater as trash, realistic, blending with the marine environment",
    19: "a piece of wreckage underwater, realistic, blending with the marine environment",
    20: "a tarp as trash underwater, realistic, blending with the marine environment",
    21: "a rope tangled underwater as trash, realistic, blending with the marine environment",
    22: "a fishing net tangled underwater as trash, realistic, blending with the marine environment",
}

prompts_v2 = {
    1: "a large underwater remotely operated vehicle (ROV), prominently centered, detailed, and realistic, surrounded by a natural marine environment",
    2: "a large underwater plant, swaying gently, prominently visible and detailed, surrounded by a natural marine environment",
    3: "a brightly colored fish swimming prominently underwater, highly detailed and realistic, surrounded by a natural marine environment",
    4: "a brightly colored starfish, prominently visible and detailed, resting on the sandy seabed surrounded by natural marine plants",
    5: "a collection of large, detailed underwater shells on the seabed, prominently visible, surrounded by a natural marine environment",
    6: "an animal crab walking prominently on the ocean floor, detailed and realistic, clearly visible",
    7: "a long eel hiding visibly in rocks or coral underwater, highly detailed and realistic, blending with the natural marine environment",
    8: "a small, unique underwater animal, prominently centered, highly detailed and realistic, surrounded by a natural marine environment",
    9: "a piece of discarded clothing underwater, prominently visible and detailed, lying on the ocean floor surrounded by marine plants and fish",
    10: "a large metal pipe as trash underwater, prominently centered, highly detailed and realistic, surrounded by the ocean floor",
    11: "a large discarded bottle underwater, prominently visible and detailed, lying on the ocean floor surrounded by a natural marine environment",
    12: "a floating plastic bag as trash underwater, clearly visible and detailed, swaying gently, surrounded by a natural marine environment",
    13: "a brightly colored snack wrapper as trash underwater, prominently visible and detailed, resting on the ocean floor surrounded by marine plants",
    14: "a large discarded can as trash underwater, prominently centered, highly detailed and realistic, lying on the ocean floor",
    15: "a plastic cup as trash underwater, prominently visible and detailed, lying on the sandy seabed surrounded by marine life",
    16: "a large container as trash underwater, prominently visible and detailed, resting on the ocean floor surrounded by a natural marine environment",
    17: "a large plastic trash object underwater, prominently centered, highly detailed and realistic, surrounded by marine plants and fish",
    18: "a floating branch underwater as trash, clearly visible and detailed, surrounded by a natural marine environment",
    19: "a large piece of wreckage underwater, prominently visible and detailed, resting on the seabed surrounded by marine plants and sand",
    20: "a large tarp as trash underwater, prominently centered, highly detailed and realistic, lying on the ocean floor surrounded by marine life",
    21: "a tangled rope underwater as trash, prominently visible and detailed, lying on the seabed surrounded by marine plants",
    22: "a large fishing net tangled underwater as trash, clearly visible and detailed, resting on the ocean floor surrounded by a natural marine environment",
}
